name: Build and Push Backstage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get ACR credentials from Azure Key Vault
        id: acr-secrets
        uses: azure/keyvault@v1
        with:
          keyvault: my-keyvault-name
          secrets: ACR-USERNAME,ACR-PASSWORD,ACR-LOGIN-SERVER

      - name: Set environment variables from secrets
        run: |
          echo "ACR_USERNAME=${{ steps.acr-secrets.outputs.ACR-USERNAME }}" >> $GITHUB_ENV
          echo "ACR_PASSWORD=${{ steps.acr-secrets.outputs.ACR-PASSWORD }}" >> $GITHUB_ENV
          echo "ACR_LOGIN_SERVER=${{ steps.acr-secrets.outputs.ACR-LOGIN-SERVER }}" >> $GITHUB_ENV

      - name: Set up Podman
        uses: redhat-actions/podman-setup@v1
        with:
          version: '5.0.0'

      - name: Login to ACR via Podman
        run: |
          podman login $ACR_LOGIN_SERVER -u $ACR_USERNAME -p $ACR_PASSWORD

      - name: Build Backstage image
        run: |
          IMAGE_TAG=latest
          podman build -t $ACR_LOGIN_SERVER/backstage:$IMAGE_TAG .

      - name: Push Backstage image
        run: |
          IMAGE_TAG=latest
          podman push $ACR_LOGIN_SERVER/backstage:$IMAGE_TAG
