name: Build and Push Backstage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      RESOURCE_GROUP: rg-aro-demo
      KEYVAULT_NAME: myKeyVaultDemo2
      IMAGE_NAME: backstage

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Get ACR credentials from Azure Key Vault
        id: get-secrets
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault:  'myKeyVaultDemo2'
          secrets: ACR-LOGIN-SERVER,ACR-USERNAME,ACR-PASSWORD

      - name: Generate dynamic image tag
        id: tag
        run: echo "IMAGE_TAG=hello-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Replace image tag in deployment.yaml
        run: |
          sed -i "s|REPLACE_ME|${IMAGE_TAG}|" manifests/backstage/deployment.yaml
      
      # 3. Commit and push updated YAML so ArgoCD will detect and deploy
      - name: Commit and push updated deployment.yaml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add manifests/backstage/deployment.yaml
          git commit -m "Update image tag to $IMAGE_TAG"
          git push

      - name: Install Podman
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Podman Login to ACR
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ steps.get-secrets.outputs.ACR-LOGIN-SERVER }}
          username: ${{ steps.get-secrets.outputs.ACR-USERNAME }}
          password: ${{ steps.get-secrets.outputs.ACR-PASSWORD }}

      - name: Build Backstage image
        run: |
          podman build -t ${{ steps.get-secrets.outputs.ACR-LOGIN-SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Backstage image to ACR
        run: |
          podman push ${{ steps.get-secrets.outputs.ACR-LOGIN-SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
