name: build-backstage

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write   # Required to commit updated deployment.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Git user
      run: |
        git config user.name "ci-bot"
        git config user.email "ci@ci.com"

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: false

    - name: Fetch ACR credentials from Key Vault
      id: get-secrets
      uses: azure/get-keyvault-secrets@v1
      with:
        keyvault: 'myKeyVaultDemo2'
        secrets: ACR-LOGIN-SERVER,ACR-USERNAME,ACR-PASSWORD

    - name: Install Podman
      run: |
        sudo apt update
        sudo apt install -y podman

    - name: Build container image with github.sha
      run: |
        podman build -t ${{ steps.get-secrets.outputs.ACR-LOGIN-SERVER }}/hello:${{ github.sha }} -f Dockerfile .

    - name: Login to ACR
      run: |
        podman login ${{ steps.get-secrets.outputs.ACR-LOGIN-SERVER }} \
          -u "${{ steps.get-secrets.outputs.ACR-USERNAME }}" \
          -p "${{ steps.get-secrets.outputs.ACR-PASSWORD }}"

    - name: Push image to ACR
      run: |
        podman push ${{ steps.get-secrets.outputs.ACR-LOGIN-SERVER }}/hello:${{ github.sha }}

    - name: Update deployment.yml with new image tag
      run: |
        sed -i "s|image: .*$|image: ${{ steps.get-secrets.outputs.ACR-LOGIN-SERVER }}/hello:${{ github.sha }}|" manifests/backstage/deployment.yml

    - name: Commit and push updated deployment.yml
      run: |
        git add manifests/backstage/deployment.yml
        git commit -m "Update image tag to ${{ github.sha }}"
        git push
